Update buildspecdevsecops.yml

diff --git a/configfiles/buildspecdevsecops.yml b/configfiles/buildspecdevsecops.yml
--- a/configfiles/buildspecdevsecops.yml
+++ b/configfiles/buildspecdevsecops.yml
@@ -32,21 +32,21 @@ phases:
     commands:
       - echo Running ZAP Full Scan with Ajax Spider for conducting DAST
       - cd configfiles
-      - docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t http://3.144.137.149/index.php -c tests.conf -d > report.txt
+      #- docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t http://3.144.137.149/index.php -c tests.conf -d > report.txt
       - cat report.txt
-      #- |
-      #  set +e # disable the 'exit immediately on error' option
-      #  docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py  -t http://3.144.137.149/index.php -c tests.conf -d > report.txt
-      #  if grep -q -E 'FAIL-NEW: [1-9]+' report.txt; then # check if any new failures were detected
-      #    aws s3 cp report.txt s3://devopsbucketstoragecapstone/Reports/OWASP_ZAP_Report_$(date +"%Y-%m-%d-%H-%M-%S").txt
-      #    echo "BUILD FAILED AND THE LAST KNOWN STABLE STATE WAS RESTORED BECAUSE A CRITICAL VULNERABILITY WAS DETECTED. PLEASE LOOK AT THE LATEST REPORT FOR FURTHER ANALYSIS"
-      #    cd ..        
-      #    ssh -i DevOps_Key.pem ubuntu@3.144.137.149 'sudo ./implement_rollback.sh'
-      #    exit 0
-      #  else
-      #    aws s3 cp report.txt s3://devopsbucketstoragecapstone/Reports/OWASP_ZAP_Report_$(date +"%Y-%m-%d-%H-%M-%S").txt
-      #    echo "BUILD WAS SUCCESFUL and all security standards are met and no critical vulnerabilities were detected"
-      #    exit 0
-      #  fi
-      #  set -e
+      - |
+        set +e # disable the 'exit immediately on error' option
+        docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py  -t http://3.144.137.149 -c tests.conf > report.txt
+        if grep -q -E 'FAIL-NEW: [1-9]+' report.txt; then # check if any new failures were detected
+          aws s3 cp report.txt s3://devopsbucketstoragecapstone/Reports/OWASP_ZAP_Report_$(date +"%Y-%m-%d-%H-%M-%S").txt
+          echo "BUILD FAILED AND THE LAST KNOWN STABLE STATE WAS RESTORED BECAUSE A CRITICAL VULNERABILITY WAS DETECTED. PLEASE LOOK AT THE LATEST REPORT FOR FURTHER ANALYSIS"
+          cd ..        
+          ssh -i DevOps_Key.pem ubuntu@3.144.137.149 'sudo ./implement_rollback.sh'
+          exit 0
+        else
+          aws s3 cp report.txt s3://devopsbucketstoragecapstone/Reports/OWASP_ZAP_Report_$(date +"%Y-%m-%d-%H-%M-%S").txt
+          echo "BUILD WAS SUCCESFUL and all security standards are met and no critical vulnerabilities were detected"
+          exit 0
+        fi
+        set -e
         
